on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # every hour

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.PAT }}
          image-names: "container-retention-policy"
          image-tags: "!master"  # target any image that has a tag starting with the word test or dev
          cut-off: 1w
          dry-run: false
          keep-n-most-recent: 4
